site_name: xleda
docs_dir: docs
site_url: https://infodesigner.github.io/xleda/

nav:
  - Home: index.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/rectangle_icon.png
  favicon: assets/images/rectangle_icon.png
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      accent: deep purple
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      accent: deep purple
  features:
    - toc.integrate
    - toc.follow
    - content.code.copy
    - navigation.top
    - navigation.instant
    - search.suggest


repo_url: https://github.com/InfoDesigner/xleda/
repo_name: xleda
edit_uri: "" # Hide the 'Edit this page' icon


extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: analytics

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - badges
  - include-markdown
